---
deployment:
  tasks:
    - mkdir -p /home/ogtgzxxk/meseriasi/src/storage/framework/sessions
    - mkdir -p /home/ogtgzxxk/meseriasi/src/storage/framework/views
    - mkdir -p /home/ogtgzxxk/meseriasi/src/storage/framework/cache/data
    - mkdir -p /home/ogtgzxxk/meseriasi/src/storage/app/public
    - mkdir -p /home/ogtgzxxk/meseriasi/src/storage/logs
    - chmod -R 775 /home/ogtgzxxk/meseriasi/src/storage
    - chmod -R 775 /home/ogtgzxxk/meseriasi/src/bootstrap/cache
    - /usr/local/bin/php /home/ogtgzxxk/meseriasi/src/artisan optimize:clear
    - /usr/local/bin/php /home/ogtgzxxk/meseriasi/src/artisan view:clear
    - /usr/local/bin/php /home/ogtgzxxk/meseriasi/src/artisan config:clear
    - /usr/local/bin/php /home/ogtgzxxk/meseriasi/src/artisan cache:clear
    - /usr/local/bin/php /home/ogtgzxxk/meseriasi/src/artisan route:clear
