---
deployment:
  tasks:
    - export APPPATH=/home/ogtgzxxk/meseriasi/src
    - /bin/mkdir -p $APPPATH/storage/logs
    - /bin/mkdir -p $APPPATH/storage/framework/cache
    - /bin/mkdir -p $APPPATH/storage/framework/sessions
    - /bin/mkdir -p $APPPATH/storage/framework/views
    - /bin/mkdir -p $APPPATH/bootstrap/cache